//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzaria_1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string End_Rua { get; set; }
        public string End_Num { get; set; }
        public string End_Bairro { get; set; }
        public string End_Complemento { get; set; }
        public string End_Refer { get; set; }
        public Nullable<int> DDD_1 { get; set; }
        public Nullable<int> DDD_2 { get; set; }
        public Nullable<int> DDD_3 { get; set; }
        public Nullable<int> DDD_4 { get; set; }
        public string Tel_1 { get; set; }
        public string Tel_2 { get; set; }
        public string Tel_3 { get; set; }
        public string Tel_4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
