//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzaria_1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ped_Prod
    {
        public int Id { get; set; }
        public int Id_Pedido { get; set; }
        public int Id_Produto { get; set; }
        public Nullable<bool> ProdInteiro { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
