//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzaria_1._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Ped_Prod = new HashSet<Ped_Prod>();
        }
    
        public int id { get; set; }
        public System.DateTime Dt_Pedido { get; set; }
        public decimal Valor_Pedido { get; set; }
        public string Observacao { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_Pagamento { get; set; }
        public bool Entrega { get; set; }
    
        public virtual Pagamento Pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ped_Prod> Ped_Prod { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
